export const generateReportEmailHTML = (
  userName: string,
  revenueData: any,
  lowStockData: any[]
): string => {
  const currencyFormatter = new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumSignificantDigits: 3 });
  
  return `
  <!DOCTYPE html>
  <html>
  <head>
    <style>
      body { font-family: 'Helvetica Neue', Arial, sans-serif; background-color: #f6f9fc; color: #333; margin: 0; padding: 0; }
      .container { max-width: 600px; margin: 40px auto; background: white; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 15px rgba(0,0,0,0.05); }
      .header { background: #6366f1; color: white; padding: 30px; text-align: center; }
      .header h1 { margin: 0; font-size: 24px; font-weight: 800; }
      .content { padding: 30px; line-height: 1.6; }
      .card { border: 1px solid #e2e8f0; border-radius: 8px; padding: 20px; margin-bottom: 20px; text-align: center; background: #f8fafc; }
      .stat-value { font-size: 32px; font-weight: 900; color: #6366f1; margin: 10px 0; }
      .stat-label { font-size: 14px; text-transform: uppercase; color: #64748b; font-weight: 700; letter-spacing: 1px; }
      .alert-box { background: #fef2f2; border-left: 4px solid #ef4444; padding: 15px; border-radius: 4px; margin-bottom: 20px; }
      .alert-box h3 { margin-top: 0; color: #b91c1c; }
      .footer { text-align: center; padding: 20px; font-size: 12px; color: #94a3b8; border-top: 1px solid #f1f5f9; }
    </style>
  </head>
  <body>
    <div class="container">
      <div class="header">
        <h1>MessFlow Automated Report</h1>
      </div>
      <div class="content">
        <p>Hello ${userName || 'Admin'},</p>
        <p>Here is your scheduled business intelligence summary for today.</p>

        ${revenueData ? `
        <div class="card">
          <div class="stat-label">Daily Revenue Highlights</div>
          <div class="stat-value">${currencyFormatter.format(revenueData.totalRevenue)}</div>
          <p style="color: #64748b; margin: 0; font-size: 14px;">from ${revenueData.orderCount} orders</p>
        </div>
        ` : ''}

        ${lowStockData && lowStockData.length > 0 ? `
        <div class="alert-box">
          <h3>Critical Stock Alerts</h3>
          <ul style="margin: 0; padding-left: 20px;">
            ${lowStockData.map(item => `<li><strong>${item.name}</strong> - Only ${item.stock} remaining!</li>`).join('')}
          </ul>
        </div>
        ` : ''}
        
        <p>Detailed CSV reports are attached to this email (if configured).</p>
      </div>
      <div class="footer">
        Generated by MessFlow Reporting Engine<br>
        <a href="https://messfloww.com/subscriptions" style="color:#6366f1;">Manage your subscription preferences</a>
      </div>
    </div>
  </body>
  </html>
  `;
};
